// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrlmdolcwzteqkkygsnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpybG1kb2xjd3p0ZXFra3lnc252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMTMzNDEsImV4cCI6MjA2ODg4OTM0MX0.EXUuMqwXIeHoiN_IIPjJL1WgMwnK8xXClOZyRUOUHOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});